//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEntry_Registration
    {
        public int Id { get; set; }
        public string DtpRegId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string WhatsApp { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public string Place { get; set; }
        public int IsDeleted { get; set; }
        public int DeletedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int ModifiedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DeletedDateTime { get; set; }
    }
}
