//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public int PgmId { get; set; }
        public int CourseId { get; set; }
        public int SubPgmId { get; set; }
        public int SubjectId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int DeletedBy { get; set; }
        public System.DateTime DeletedDateTime { get; set; }
        public int IsDeleted { get; set; }
        public int ClassId { get; set; }
    
        public virtual Group Group1 { get; set; }
        public virtual Group Group2 { get; set; }
    }
}
