//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_PreviousEntrance
    {
        public int Id { get; set; }
        public string RegId { get; set; }
        public string PrevEntranceExamName { get; set; }
        public string RollNo { get; set; }
        public string AttemptedYear { get; set; }
        public string Mark { get; set; }
        public string Rank { get; set; }
        public string NoOfAttempts { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IsDeleted { get; set; }
        public int IsRegistered { get; set; }
    }
}
