//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_HomeCountryDetails
    {
        public int Id { get; set; }
        public int StudRegId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AreaHome { get; set; }
        public string PincodeHome { get; set; }
        public string QuickContact { get; set; }
        public string LocationHome { get; set; }
        public string StateHome { get; set; }
        public string EmaiId { get; set; }
        public string QuickHomeWhatsapp { get; set; }
    
        public virtual Student_Registration Student_Registration { get; set; }
    }
}
