//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Parent
    {
        public int Id { get; set; }
        public string RegId { get; set; }
        public string FrName { get; set; }
        public string FrOcc { get; set; }
        public string FrMobNo { get; set; }
        public string FrMailid { get; set; }
        public string FrDistrict { get; set; }
        public string FrSign { get; set; }
        public string FrState { get; set; }
        public string FrWhatsapp { get; set; }
        public string MrName { get; set; }
        public string MrOcc { get; set; }
        public string MrMobNo { get; set; }
        public string MrMailid { get; set; }
        public string MrDistrict { get; set; }
        public string MrSign { get; set; }
        public string MrState { get; set; }
        public string MrWhatsapp { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IsDeleted { get; set; }
    }
}
