//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Registration
    {
        public int Id { get; set; }
        public string RegId { get; set; }
        public string ExamAttendingYear { get; set; }
        public string PreferredDay { get; set; }
        public string ApplnDate { get; set; }
        public string AcademicYear { get; set; }
        public string AdmissionTestDate { get; set; }
        public string StudentName { get; set; }
        public string PreferredTime { get; set; }
        public string WhatsappNo { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string Community { get; set; }
        public string BloodGroup { get; set; }
        public string Nationalty { get; set; }
        public string PresentAddress { get; set; }
        public string Area { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string QuickContNo { get; set; }
        public string Photo { get; set; }
        public string QuickWhatsApp { get; set; }
        public int PgmId { get; set; }
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public int SubPgmId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IsDeleted { get; set; }
    }
}
