//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_AcademicPerformance
    {
        public int Id { get; set; }
        public string RegId { get; set; }
        public string Class { get; set; }
        public string PassYear { get; set; }
        public string SchoolAddress { get; set; }
        public string RegNo { get; set; }
        public string Board { get; set; }
        public string PhyMark { get; set; }
        public string ChemMark { get; set; }
        public string BiologyMark { get; set; }
        public string MathsMark { get; set; }
        public string PercOfMark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IsDeleted { get; set; }
        public int IsRegistered { get; set; }
    }
}
