//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_AcademicPerformance
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Class { get; set; }
        public string PassYear { get; set; }
        public string SchoolAddress { get; set; }
        public string RegNo { get; set; }
        public string Board { get; set; }
        public Nullable<decimal> PhyMark { get; set; }
        public Nullable<decimal> ChemMark { get; set; }
        public Nullable<decimal> BiologyMark { get; set; }
        public Nullable<decimal> MathsMark { get; set; }
        public Nullable<decimal> PercOfMark { get; set; }
    
        public virtual User User { get; set; }
    }
}
