//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Registration()
        {
            this.Student_AcademicPerformance = new HashSet<Student_AcademicPerformance>();
            this.Student_HomeCountryDetails = new HashSet<Student_HomeCountryDetails>();
            this.Student_Parent = new HashSet<Student_Parent>();
            this.Student_PreviousEntrance = new HashSet<Student_PreviousEntrance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int GroupId { get; set; }
        public int BatchId { get; set; }
        public string ExamAttendingYear { get; set; }
        public string PreferredDay { get; set; }
        public System.DateTime ApplnDate { get; set; }
        public string AcademicYear { get; set; }
        public System.DateTime AdmissionTestDate { get; set; }
        public System.TimeSpan PreferredTime { get; set; }
        public string WhatsappNo { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string Community { get; set; }
        public string BloodGroup { get; set; }
        public string Nationalty { get; set; }
        public string PresentAddress { get; set; }
        public string Area { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string QuickContNo { get; set; }
        public string Photo { get; set; }
        public string QuickWhatsApp { get; set; }
        public int PgmId { get; set; }
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public int SubPgmId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_AcademicPerformance> Student_AcademicPerformance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_HomeCountryDetails> Student_HomeCountryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Parent> Student_Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_PreviousEntrance> Student_PreviousEntrance { get; set; }
    }
}
